import type { View } from '@storybook/react-native';

// `storybook.requires.js` is generated by Storybook (as JS, so the generated `require` calls pass
// the repo's lint rules). This declares the one export the app reads.
export const view: View;
